"use client";

import { useState } from "react";
import { Check, LoaderCircle, Save, SlidersHorizontal } from "lucide-react";

interface Settings { maxRetryAttempts: number; minConfidenceThreshold: number; autoRecoveryEnabled: boolean; alternatePaymentEnabled: boolean; paymentLinkEnabled: boolean; notificationsEnabled: boolean }

export function SettingsForm({ initialSettings }: { initialSettings: Settings }) {
  const [settings, setSettings] = useState(initialSettings);
  const [saving, setSaving] = useState(false);
  const [feedback, setFeedback] = useState<{ type: "success" | "error"; text: string } | null>(null);
  async function saveSettings() {
    setSaving(true); setFeedback(null);
    try { const response = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Could not save settings."); setFeedback({ type: "success", text: "Settings saved successfully." }); }
    catch (error) { setFeedback({ type: "error", text: error instanceof Error ? error.message : "Could not save settings." }); }
    finally { setSaving(false); }
  }
  return <div className="mt-10 max-w-3xl rounded-xl border border-white/10 bg-[#111a23] p-6 sm:p-8"><div className="flex items-center gap-3"><SlidersHorizontal className="text-[#b8f36b]" size={20} /><h2 className="text-lg font-semibold">Recovery guardrails</h2></div><div className="mt-8 space-y-8"><Range label="Maximum retry attempts" value={settings.maxRetryAttempts} min={1} max={5} suffix=" attempts" onChange={(value) => setSettings({ ...settings, maxRetryAttempts: value })} /><Range label="Minimum confidence threshold" value={settings.minConfidenceThreshold} min={50} max={95} suffix="%" onChange={(value) => setSettings({ ...settings, minConfidenceThreshold: value })} /></div><div className="mt-10 border-t border-white/10 pt-5"><Toggle label="Auto-recovery" description="Execute eligible recovery actions automatically." value={settings.autoRecoveryEnabled} onChange={(value) => setSettings({ ...settings, autoRecoveryEnabled: value })} /><Toggle label="Alternate payment recommendations" description="Suggest another payment path after failure." value={settings.alternatePaymentEnabled} onChange={(value) => setSettings({ ...settings, alternatePaymentEnabled: value })} /><Toggle label="Payment link recovery" description="Allow the agent to send a new payment link." value={settings.paymentLinkEnabled} onChange={(value) => setSettings({ ...settings, paymentLinkEnabled: value })} /><Toggle label="Notifications" description="Notify the merchant when human attention is needed." value={settings.notificationsEnabled} onChange={(value) => setSettings({ ...settings, notificationsEnabled: value })} /></div><button type="button" onClick={saveSettings} disabled={saving} className="mt-8 inline-flex h-11 items-center gap-2 rounded-lg bg-[#b8f36b] px-5 text-sm font-semibold text-[#0c1118] disabled:opacity-50">{saving ? <LoaderCircle size={17} className="animate-spin" /> : <Save size={17} />}{saving ? "Saving..." : "Save settings"}</button>{feedback && <p className={`mt-4 flex items-center gap-2 text-sm ${feedback.type === "success" ? "text-emerald-300" : "text-red-300"}`}>{feedback.type === "success" && <Check size={16} />}{feedback.text}</p>}</div>;
}

function Range({ label, value, min, max, suffix, onChange }: { label: string; value: number; min: number; max: number; suffix: string; onChange: (value: number) => void }) { return <label className="block"><span className="flex justify-between text-sm"><span className="text-slate-300">{label}</span><span className="font-semibold text-[#b8f36b]">{value}{suffix}</span></span><input className="mt-4 w-full accent-[#b8f36b]" type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
function Toggle({ label, description, value, onChange }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-start justify-between gap-4 border-b border-white/[0.06] py-4 last:border-0"><div><p className="text-sm font-medium text-slate-200">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div><button type="button" role="switch" aria-checked={value} onClick={() => onChange(!value)} className={`relative mt-1 h-6 w-11 shrink-0 rounded-full ${value ? "bg-[#b8f36b]" : "bg-white/15"}`}><span className={`absolute top-1 size-4 rounded-full bg-[#0c1118] transition-transform ${value ? "translate-x-6" : "translate-x-1"}`} /></button></div>; }